---
extends:
  - eslint:recommended
  - ./eslint/node.yml
  - ./eslint/js.yml
parser: babel-eslint
env:
  es6: true
  node: true
  mocha: true
globals:
  mount: true
  shallow: true
  enableDeepSnapshots: true
  ruleHelpers: true
rules:
  no-console: 0
  no-underscore-dangle: 0
  no-unused-vars:
    - error
    - argsIgnorePattern: next
  no-use-before-define:
    - error
    - variables: false
  no-multi-str: 0
  consistent-return: 'off'
